version: '3.4'

services:
  checkout.paymentgateway.api:
    image: ${DOCKER_REGISTRY-}checkoutpaymentgatewayapi
    build:
      context: .
      dockerfile: Checkout.PaymentGateway.Api/Dockerfile

  checkout.paymentgateway.identityserver:
    image: ${DOCKER_REGISTRY-}checkoutpaymentgatewayidentityserver
    build:
      context: .
      dockerfile: Checkout.PaymentGateway.IdentityServer/Dockerfile

